# Generated by Django 2.0.5 on 2018-05-14 23:45

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=5, verbose_name='Country')),
                ('street', models.CharField(max_length=50, verbose_name='Street Address')),
                ('city', models.CharField(max_length=40, verbose_name='City')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('department', models.CharField(max_length=50, verbose_name='Department')),
                ('district', models.CharField(max_length=50, verbose_name='District')),
                ('prefecture', models.CharField(max_length=50, verbose_name='Prefecture')),
                ('province', models.CharField(max_length=50, verbose_name='Province')),
                ('region', models.CharField(max_length=50, verbose_name='Region')),
                ('municipality', models.CharField(max_length=50, verbose_name='Municipality')),
                ('county', models.CharField(max_length=50, verbose_name='County')),
                ('nation', models.CharField(max_length=50, verbose_name='Nation')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('mobile_phone', models.CharField(blank=True, max_length=30, verbose_name='Mobile Phone Number')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Create Timestamp')),
                ('modified_timestamp', models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('desciption', models.CharField(blank=True, max_length=256, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attribute',
            },
        ),
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Create Timestamp')),
                ('modified_timestamp', models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('desciption', models.CharField(max_length=256, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'AttributeType',
                'verbose_name_plural': 'AttributeType',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=75, verbose_name='Last Name')),
                ('company', models.CharField(max_length=150, verbose_name='Company')),
                ('email', models.CharField(max_length=255, verbose_name='Email Address')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Create Timestamp')),
                ('modified_timestamp', models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('status', models.PositiveIntegerField(verbose_name='Status')),
                ('bill_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_to_set', to='store.Address', verbose_name='Bill To')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Contact', verbose_name='Contact')),
                ('ship_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_to_set', to='store.Address', verbose_name='Ship To')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Create Timestamp')),
                ('modified_timestamp', models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp')),
                ('price', models.DecimalField(decimal_places=8, max_digits=8, verbose_name='Price')),
                ('currency', models.CharField(choices=[('BTC', 'BitCoin')], max_length=3, verbose_name='Currency')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('ordering', models.PositiveIntegerField(verbose_name='Ordering')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'OrderLine',
                'verbose_name_plural': 'OrderLines',
            },
        ),
        migrations.CreateModel(
            name='OrderLineShippingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Create Timestamp')),
                ('modified_timestamp', models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Awaiting Fulfillment'), (2, 'Awaiting Shipment'), (3, 'Shipped'), (4, 'Completed'), (5, 'Backordered'), (6, 'Cancelled'), (7, 'Refunded')], verbose_name='Status')),
                ('tracking', models.CharField(default='', max_length=100, verbose_name='Tracking')),
            ],
            options={
                'verbose_name': 'OrderLineShippingInfo',
                'verbose_name_plural': 'OrderLineShippingInfos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Create Timestamp')),
                ('modified_timestamp', models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('desciption', models.CharField(max_length=256, verbose_name='Description')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Create Timestamp')),
                ('modified_timestamp', models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('desciption', models.CharField(max_length=256, verbose_name='Description')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.ProductCategory', verbose_name='Parent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Create Timestamp')),
                ('modified_timestamp', models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp')),
                ('number', models.CharField(max_length=40, verbose_name='Number')),
                ('price', models.DecimalField(decimal_places=8, max_digits=8, verbose_name='Price')),
                ('currency', models.CharField(choices=[('BTC', 'BitCoin')], max_length=3, verbose_name='Currency')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('attributes', models.ManyToManyField(to='store.Attribute', verbose_name='Attributes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKU',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.ProductCategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.SKU', verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.AttributeType', verbose_name='Type'),
        ),
    ]
