# Generated by Django 2.0.5 on 2018-05-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20180517_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Number'),
        ),
    ]
