# Generated by Django 2.0.5 on 2018-05-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='desciption',
            new_name='description',
        ),
    ]
