# Generated by Django 2.0.5 on 2018-05-17 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20180517_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributetype',
            old_name='desciption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='store.AttributeType', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='attributes',
            field=models.ManyToManyField(related_name='sku_set', to='store.Attribute', verbose_name='Attributes'),
        ),
    ]
