# Generated by Django 2.0.5 on 2018-05-18 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20180517_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='full_name',
            field=models.CharField(default='default', max_length=150, verbose_name='Full Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribute_set', to='store.AttributeType', verbose_name='Type'),
        ),
    ]
