# Generated by Django 2.0.5 on 2018-05-18 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20180518_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='modified_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp'),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='modified_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp'),
        ),
    ]
