# Generated by Django 2.0.5 on 2018-05-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20180518_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderLineShippingInfo',
        ),
    ]
