# Generated by Django 2.0.5 on 2018-05-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_delete_orderlineshippinginfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='desciption',
            new_name='description',
        ),
    ]
